#!/usr/bin/env bash
# prints details about the subdomains of a provided domain

subdomains=( "www" "lb-01" "web-01" "web-02" )

dominfo () {
    local domain="$1"
    local subdomain="$2"
    local output
    output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1)
    if [ -n "$output" ]; then
        echo "$output" | awk '{print "The subdomain " "'$subdomain'" " is a " $4 " record and points to " $5}'
    fi
}

if [ $# -eq 1 ]; then
    for sub in "${subdomains[@]}"; do
        dominfo "$1" "$sub"
    done
elif [ $# -eq 2 ]; then
    dominfo "$1" "$2"
fi
