#!/usr/bin/env bash
# listens on port 80

sudo apt-get update
sudo apt-get install nginx -y

sudo ufw enable
sudo ufw allow 'Nginx HTTP'

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo chmod 777 /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

sudo chmod 777 /etc/nginx/nginx.conf
printf %s "http {
        server {
            listen 80;
            root /etc/nginx/html;
        }
}
events {}" | sudo tee /etc/nginx/nginx.conf

sudo nginx -s reload
clear
curl localhost:80
