#!/usr/bin/env bash
# listens on port 80

sudo apt-get update
sudo apt-get install nginx -y

# sudo ufw enable
# sudo ufw allow 'Nginx HTTP'

sudo mkdir "/etc/nginx/html"
sudo echo "Hello World!" > "/etc/nginx/html/index.html"
sudo printf %s "http {
        server {
            listen 80;
            root /etc/nginx/html;
        }
}" > "/etc/nginx/nginx.conf"

sudo nginx -s reload

curl localhost:80
