#!/usr/bin/env bash
# installs nginx and configures a redirect

apt-get update -y -qq
apt-get install nginx -y


service nginx start
ufw allow 'Nginx HTTP'

chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=xvFZjo5PgG0 permanent;' /etc/nginx/sites-available/default

service nginx restart
