#!/usr/bin/env bash
# configures a custom 404 page

apt-get update -y
apt-get install nginx -y


service nginx start
sudo ufw allow 'Nginx HTTP'

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i '24i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=xvFZjo5PgG0 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sed -i '25i\ error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
