#! /usr/bin/env bash
# configure a new ubuntu system to fit the requirments

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/ww/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404error.html

sed -i "34i\ # custom configurations" /etc/nginx/sites-available/default
sed -i "34i\/\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n" /etc/nginx/sites-available/default
sed -i "34i\/\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sed -i "34i\/\n\tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-available/default

service nginx restart
