#!/usr/bin/env bash
# trasnfers a file from client to server. 
# USAGE: 0-transfer_file 1PATH_TO_FILE 2IP 3USERNAME 4PATH_TO_SSH_KEY

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:$1"
fi
