#!/usr/bin/env bash
# file test operators

if [ -e "$1" ]; then
  echo "school file exists" 
else
  echo "school file does not exist"
fi

if [ ! -s "$1" ]; then
  echo "school file is empty" 
else
  echo "school file is not empty"
fi

if [ -f "$1" ]; then
  echo "school file is a regular file" 
fi
